travis:
  secure:
    BINSTAR_TOKEN: sdXP5S/K6nWoUNqHhZ1BSbNB/lfBooqKgeNWRn7kAskvVWo5nESpfp0AyNbE/KL+gzjp/+PyjZbckA+hW+CCWYL6IigQZFV1EoxrZKuPCrRlnoZQBqai1kCMvKuYswI5yyB0twoq/RskdZuBLqpp3ZOv6IhNCX7xYZBQRhh/DlwOHZjDPhv8o4Nn92pLTL9e3pPuD0HvTz+RbfMo2viSVdz0h6SG9WEvD/wxYSH3rLcnY7IwcN7Ssl6+se/03w5WoDNfN9ccbQGgIYc/xBgadbu5tVQddsx5sMqR6ENFklE1vZJqvPIs/zr4N6nmBY5pz7VHOQnRhOlyqr671n4qsue7eS8FOsSykEKpWlaOlbj04qxrgquC7I9VRfxuVXBZKdOcqWIZQLz7UCvr8HS5iIARVtbRFdvxmC/0QC2og3Alrlso7vdwoGbeGFuOqGxcBhRrLf5BiJgB0jmITcGkiz7lPIH6ikPq+WpKkNhtegMnEZmfjJQKMkAQNwqc0s8WvkwdXxBd7XixgyXRR2FnzC8lHXx7rfBciJHXtWTf71RYTlUCRnPcmFEJdWj+s1PSomRdyQCZfhk/8w+q03CbMjSGwTz6Llbizh+yE83O7H9mbBE3Iqn+b7cVIhr2WO1iDb8bojoGhDbYfRBmvh2RRMwogBwnxaYEECSareZkrZs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
