travis:
  secure:
    BINSTAR_TOKEN: e1Dm7YP0G9iaGPJKvD1hGZG98Gj6yOjWpSb1EIRPYEwvGVhaX0cdS/hqf0ZN7IlxiHNnti51uA+Dzkg2m3Cta4V4wE6BRpFu52mbCWCp/qaB2ecM9L7OZJ9QKjjmgjh6CMZ2/jqxL9FPDWqh3Q5g9Z82X+Ixqp0WEusOmeIt7WuVwqQcmU5ypJNxoISwE3V2IfMuqdc6+jKt40A+7NUBESbAz7BxhP5pIvSwwgp/q6YOFEM/HdxIk88QOkMpQcSt3wmEYkHVCxDFx78joc5iF0TyZpnVxQwUNUq+0osSfSV5cUqFahR0DCNYBDwH41y8ws0wljbP58OPSNFZJYozrAu08W4oM3wNb6dWQXeT7Us/0e/RknrXv4C4/RBYxg8pVZKdSQ2hcnNm76/MnY4teSEpYSoz62ystaWm0q4ZujuNOaPoCWdnav/ROdgy3xvXbypcAUC2Z13zfZ6e+R6lwM68Lj0UaBtmrjO/SLOnObKXlumf+GYI1L3hJhwQTcwWeVdv9UnpAbFtsC5NIGLTD7m5abSMd7xgHFATCqRHxBUQZPAGxxWHi0l1zhqEOORUZLxvblbgcQqR+8FqC2NSCJCRSPjWxaP5Dzo1ZlXGcFUTpidRJ7/lSATeVMsaK5YYYbXuQ6ue7f3L6jMpGjB25cES68Le2Lwp/MciyM2FjhE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
